name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.MD
      - .github/workflows/DockerHub-Description.yml
jobs:
  dockerHubDescription:
    if: startsWith(github.repository, 'Binaryify/NeteaseCloudMusicApi')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@579f64ca0abced29dbbc44ab4c6a0b9e33ab3588 # v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: binaryify/netease_cloud_music_api
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.MD
